### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by jonboulle** [appc/goaci#10]
It would be really great if goaci could produce deterministic, reproducible ACI builds from a given snapshot (e.g. git sha) of a particular Go project.

This will require:
- [ ] ensuring the actual go build is deterministic and reproducible (discussion [here](https://groups.google.com/d/msg/golang-nuts/8zXtSj8-YjQ/8wqqrn7gZRwJ), [here](https://github.com/golang/go/issues/9206))
- [ ] deterministic manifest creation ([canonical JSON](http://wiki.laptop.org/go/Canonical_JSON)? - this would be nice upstream in appc/spec) 
- [ ] deterministic tar creation (see, e.g., https://github.com/appc/spec/issues/199)
- [ ] not leaking uid/gid of the builder in the aci (see #16 )
